# -*- coding: utf-8 -*-
"""SENAI-Python-Lista-Atividades-9-REGRESSAO_LINEAR-MULTIPLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wpxz_2NmrgA9wMbrZU7g988PTC9Gf1Eh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = np.genfromtxt('dados_descarbonizacao.csv', delimiter=',', skip_header=1)

#df = pd.read_csv('dados_descarbonizacao.csv', header=None)
#df = df.drop(0)
#tresPrimeiras = df.head(3)

df

x = df[:,:4]
y = df[:,4:]

X = np.hstack((np.ones((len(x),1)),x))
betas, res, _, _ = np.linalg.lstsq(X, y, rcond=None)
residuo = res[0]

yPrev = X @ betas

yMedio = np.mean(y)
tss = np.sum((y - yMedio) ** 2) # Soma total dos quadrados
rss = np.sum((y - yPrev) ** 2) # residuo dos quadrados
r2 = 1 - rss / tss

print(r2)

print('Real Predito Diferença Relativa (%)')
for real, pred in zip(y, yPrev):
  print(f'{real[0]:.0f} {pred[0]:.0f}'
  f'{100*(pred [0] - real[0]) / real[0]:4.1f}')